### ISSUE TITLE
请问后续有V2.0的文档的翻译吗

### ISSUE THREAD

**Issue by jwma2012** [TechCatsLab/cockroachdb_docs_cn#1]
RT，谢谢啦，有的话，我可以加入帮忙翻译，大家相互学习，我最近也在看这个。

**Comment by Txiaozhe** [comment]
更多关于cockroachdb的中文信息，请关注cockroachdb中国社区网站
http://www.cockroachchina.cn/
会不定期更新文档和相关技术文章
